version: '2'
services:
  shopfront-dev:
    image: cbonami/shopfront
    ports:
     - "8010:8010"
     - "8011:8011"
    links:
      - productcatalogue
      - stockmanager
  productcatalogue:
    image: cbonami/productcatalogue
    ports:
     - "8020:8020"
     - "8021:8021"
  stockmanager:
    image: cbonami/stockmanager
    ports:
     - "8030:8030" 
     - "8031:8031"
