version: '2'
services:
  shopfront:
    image: cbonami/djshopfront
    ports:
     - "8010:8010"
    links:
      - productcatalogue
      - stockmanager
  productcatalogue:
    image: cbonami/djproductcatalogue
    ports:
     - "8020:8020"
  stockmanager:
    image: cbonami/djstockmanager
    ports:
     - "8030:8030" 
